package componentize-py:test

interface simple-import-and-export {
    foo: func(v: u32) -> u32
}

world simple-import-and-export-test {
    import simple-import-and-export
    export simple-import-and-export
}
