from typing import Any
from componentize_py_types import Result

def call_task_return(index: int, borrows: int, result: Any) -> None: ...

def waitable_set_drop(set: int) -> None: ...

def context_set(value: Any) -> None: ...

def context_get() -> Any: ...

def waitable_join(waitable: int, set: int) -> None: ...

def subtask_drop(task: int) -> None: ...

def waitable_set_new() -> int: ...

def promise_get_result(event: int, promise: int) -> Any: ...

def future_read(ty: int, future: int) -> Result[Any, tuple[int, int]]: ...

def future_write(ty: int, future: int, value: Any) -> Result[tuple[int, int], tuple[int, int]]: ...

def future_drop_readable(ty: int, future: int) -> None: ...

def future_drop_writable(ty: int, future: int) -> None: ...

def stream_read(ty: int, stream: int, max_count: int) -> Result[tuple[int, bytes | list[Any]], tuple[int, int]]: ...

def stream_write(ty: int, stream: int, values: bytes | list[Any]) -> Result[tuple[int, int], tuple[int, int]]: ...

def stream_drop_readable(ty: int, stream: int) -> None: ...

def stream_drop_writable(ty: int, stream: int) -> None: ...
