"""Registry of the implementations an app provides for its WIT exports.

The bindings generated by `componentize-py` include a decorator for each
exported interface, resource, and world, and applying one of those decorators
registers the decorated class here.  `componentize-py` reads this registry when
pre-initializing the component in order to connect each WIT export to the code
implementing it.

Application code should not use this module directly; use the generated
decorators instead, e.g.::

    from wit.exports.wasi.http_v0_2 import incoming_handler

    @incoming_handler.guest
    class MyHandler:
        ...
"""

from typing import Any, Callable, Dict, TypeVar

T = TypeVar("T")

# Export key (see `scope` in `init.wit`) -> implementing class.
EXPORTS: Dict[str, Any] = {}


def register(key: str) -> Callable[[T], T]:
    """Return a decorator which registers the class it's applied to as the
    implementation of the WIT export named by `key`."""

    def decorate(value: T) -> T:
        if key in EXPORTS:
            raise RuntimeError(
                f"multiple implementations registered for `{key}`; "
                f"exactly one is expected"
            )
        EXPORTS[key] = value
        return value

    return decorate
