package componentize-py:init;

world init {
    import wasi:cli/environment@0.2.0;

    export exports: interface {
        record bundled {
            module: string,
            protocol: string,
            name: string
        }

        record function {
            protocol: string,
            name: string
        }

        record %constructor {
            module: string,
            protocol: string
        }

        record %static {
            module: string,
            protocol: string,
            name: string
        }

        variant function-export {
            bundled(bundled),
            freestanding(function),
            %constructor(%constructor),
            %method(string),
            %static(%static)
        }

        record case {
            name: string,
            has-payload: bool,
        }

        record local-resource {
            new: u32,
            rep: u32,
            drop: u32
        }

        record remote-resource {
            drop: u32
        }
        
        record %resource {
            local: option<local-resource>,
            remote: option<remote-resource>
        }

        variant owned-kind {
            %record(list<string>),
            %variant(list<case>),
            %enum(u32),
            %flags(u32),
            %resource(%resource),
        }

        record owned-type {
            kind: owned-kind,
            %package: string,
            name: string
        }

        variant %type {
            owned(owned-type),
            %option,
            nesting-option,
            %result,
            %tuple(u32),
            handle
        }

        record symbols {
            types-package: string,
            exports: list<function-export>,
            types: list<%type>
        }

        init: func(app-name: string, symbols: symbols, stub-wasi: bool) -> result<_, string>;
    }
}
