use {
    crate::{BindingsGenerator, ComponentGenerator},
    anyhow::{Context, Result},
    clap::Parser as _,
    std::{
        env,
        ffi::OsString,
        fs,
        path::{Path, PathBuf},
        process, str,
    },
    tokio::runtime::Runtime,
};

/// A utility to convert Python apps into Wasm components
#[derive(clap::Parser, Debug)]
#[command(author, version, about)]
pub struct Options {
    #[command(flatten)]
    pub common: Common,

    #[command(flatten)]
    pub deprecated: Deprecated,

    #[command(subcommand)]
    pub command: Command,
}

/// Options kept only for back-compat; `run` folds them into `Common`.
#[derive(clap::Args, Clone, Debug)]
pub struct Deprecated {
    /// Deprecated: renamed to `--bindings-module`.
    #[arg(long, hide = true)]
    pub world_module: Option<String>,

    /// Deprecated and ignored: fully-qualified module names are always used.
    #[arg(long, hide = true, action = clap::ArgAction::SetTrue)]
    pub full_names: Option<bool>,
}

#[derive(clap::Args, Clone, Debug)]
pub struct Common {
    /// Files or directories containing WIT document(s).
    ///
    /// This may be specified more than once, for example:
    /// `-d ./wit/deps -d ./wit/app`
    #[arg(short = 'd', long)]
    pub wit_path: Vec<PathBuf>,

    /// Name of world to target (or default world if not specified).
    ///
    /// This may be specified more than once, in which case the worlds will be
    /// merged.
    #[arg(short = 'w', long)]
    pub world: Vec<String>,

    /// Disable non-error output
    #[arg(short = 'q', long)]
    pub quiet: bool,

    /// Comma-separated list of features that should be enabled when processing
    /// WIT files.
    ///
    /// This enables using `@unstable` annotations in WIT files.
    #[clap(long)]
    features: Vec<String>,

    /// Whether or not to activate all WIT features when processing WIT files.
    ///
    /// This enables using `@unstable` annotations in WIT files.
    #[clap(long)]
    all_features: bool,

    /// Specify names to use for imported interfaces.  May be specified more
    /// than once.
    ///
    /// By default, the Python module generated for a given interface is nested
    /// according to the fully-qualified WIT interface name, i.e. the package
    /// namespace, then the package name plus its (semver-canonical) version,
    /// then the interface name (e.g. `wit.imports.wasi.http_v0_2.types` for
    /// `wasi:http/types@0.2.0`).  With this option, you may override that with
    /// your own, unique name, which may itself be a dotted path (e.g.
    /// `my_package.my_module`) and is used verbatim. Each component must be a
    /// valid Python identifier.
    #[arg(long, value_parser = parse_key_value)]
    pub import_interface_name: Vec<(String, String)>,

    /// Specify names to use for exported interfaces.  May be specified more
    /// than once.
    ///
    /// By default, the Python module generated for a given interface is nested
    /// according to the fully-qualified WIT interface name, i.e. the package
    /// namespace, then the package name plus its (semver-canonical) version,
    /// then the interface name (e.g. `wit.exports.wasi.http_v0_2.types` for
    /// `wasi:http/types@0.2.0`).  With this option, you may override that with
    /// your own, unique name, which may itself be a dotted path (e.g.
    /// `my_package.my_module`) and is used verbatim. Each component must be a
    /// valid Python identifier.
    #[arg(long, value_parser = parse_key_value)]
    pub export_interface_name: Vec<(String, String)>,

    /// Optional name of top-level module to use for bindings.
    ///
    /// If this is not specified, the module name will default to "wit".
    #[arg(long)]
    pub bindings_module: Option<String>,
}

#[derive(clap::Subcommand, Debug)]
pub enum Command {
    /// Generate a component from the specified Python app and its dependencies.
    Componentize(Componentize),

    /// Generate Python bindings for the world and write them to the specified
    /// directory.
    ///
    /// Note that bindings generated using this command are only stubs which
    /// unconditionally raise `NotImplementedError`s.  They are meant for use by
    /// e.g. IDEs, type checkers, and document generators.  The `componentize`
    /// subcommand will generate the real code (i.e. code connected to the
    /// components actual imports and exports) on-the-fly as necessary.  The
    /// bindings generated by this command need not and should not be used by an
    /// actual component produced using the `componentize` command.
    Bindings(Bindings),
}

#[derive(clap::Args, Debug)]
pub struct Componentize {
    /// The name of a Python module containing the app to wrap.
    ///
    /// Note that this should not match the bindings module name (`wit` by
    /// default, see `--bindings-module`), since Python can't load two
    /// top-level modules with the same name.
    pub app_name: String,

    /// Specify a directory containing the app and/or its dependencies.  May be
    /// specified more than once.
    ///
    /// If a `VIRTUAL_ENV` environment variable is set, it will be interpreted
    /// as a directory name, and that directory will be searched for a
    /// `site-packages` subdirectory, which will be appended to the path as a
    /// convenience for `venv` users.  Alternatively, if `pipenv` is in `$PATH`
    /// and `pipenv --venv` produces a non-empty result, it will be searched for
    /// a `site-packages` subdirectory, which will likewise be appended.  If the
    /// previous options fail, the `site` module in python will be used to get
    /// the `site-packages`
    #[arg(short = 'p', long, default_value = ".")]
    pub python_path: Vec<String>,

    /// Specify which world to use with which Python module.  May be specified
    /// more than once.
    ///
    /// Some Python modules (e.g. SDK wrappers around WIT APIs) may contain
    /// `componentize-py.toml` files which point to embedded WIT files, and
    /// those may define multiple WIT worlds.  In this case, it may be necessary
    /// to specify which world on a module-by-module basis.
    ///
    /// Note that these must be specified in topological order (i.e. if a module
    /// containing WIT files depends on other modules containing WIT files, it
    /// must be listed after all its dependencies).
    #[arg(short = 'm', long, value_parser = parse_key_value)]
    pub module_worlds: Vec<(String, String)>,

    /// Specify a world to *intersect* with the world(s) specified elsewhere.
    ///
    /// The `--world` option, `--module-worlds` option, and
    /// `componentize-py.toml` files may be used to specify any number of worlds
    /// for the component to target.  If more than one are specified, they are
    /// unioned together to compute the target world.  This option extends that
    /// computation to calculate the *intersection* (i.e. shared subset) of that
    /// union and the specified world.
    ///
    /// This can be useful in cases where an application is using an SDK lbirary
    /// containing a `componentize-py.toml` and pre-generated bindings, but the
    /// target environment for the app only supports a subset of the features
    /// covered by the SDK.  By default, using that SDK would pull in all the
    /// imports of the world(s) for which it was intended, but with this option,
    /// we can exclude imports that are unsupported by the target environment
    /// and still use the subset of the SDK which does not require those
    /// excluded imports.
    ///
    /// Note that this may lead to pre-init or runtime errors if the application
    /// does in fact end up using any imports which were excluded.
    #[arg(short = 'i', long)]
    pub intersect_world: Option<String>,

    /// Output file to which to write the resulting component
    #[arg(short = 'o', long, default_value = "index.wasm")]
    pub output: PathBuf,

    /// If set, replace all WASI imports with trapping stubs.
    ///
    /// PLEASE NOTE: This has the effect of baking whatever PRNG seed is
    /// generated at build time into the component, meaning Python's `random`
    /// module will return the exact same sequence each time the component is
    /// run.  Do *not* use this option in situations where a secure source of
    /// randomness is required.
    #[arg(short = 's', long)]
    pub stub_wasi: bool,
}

#[derive(clap::Args, Debug)]
pub struct Bindings {
    /// Directory to which bindings should be written.
    ///
    /// This will be created if it does not already exist.
    pub output_dir: PathBuf,
}

fn parse_key_value(s: &str) -> Result<(String, String), String> {
    let (k, v) = s
        .split_once('=')
        .ok_or_else(|| format!("expected string of form `<key>=<value>`; got `{s}`"))?;
    Ok((k.to_string(), v.to_string()))
}

pub fn run<T: Into<OsString> + Clone, I: IntoIterator<Item = T>>(args: I) -> Result<()> {
    let Options {
        mut common,
        deprecated,
        command,
    } = Options::parse_from(args);

    common.bindings_module = crate::resolve_deprecated(
        common.bindings_module,
        deprecated.world_module,
        deprecated.full_names,
        common.quiet,
    )?;

    match command {
        Command::Componentize(opts) => componentize(common, opts),
        Command::Bindings(opts) => generate_bindings(common, opts),
    }
}

fn generate_bindings(common: Common, bindings: Bindings) -> Result<()> {
    BindingsGenerator {
        wit_paths: &common
            .wit_path
            .iter()
            .map(|v| v.as_path())
            .collect::<Vec<_>>(),
        worlds: &common.world.iter().map(|v| v.as_str()).collect::<Vec<_>>(),
        features: &common
            .features
            .iter()
            .map(|v| v.as_str())
            .collect::<Vec<_>>(),
        all_features: common.all_features,
        bindings_module: common.bindings_module.as_deref(),
        output_dir: &bindings.output_dir,
        import_interface_names: &common
            .import_interface_name
            .iter()
            .map(|(a, b)| (a.as_str(), b.as_str()))
            .collect(),
        export_interface_names: &common
            .export_interface_name
            .iter()
            .map(|(a, b)| (a.as_str(), b.as_str()))
            .collect(),
    }
    .generate()
}

fn componentize(common: Common, componentize: Componentize) -> Result<()> {
    let mut python_path = componentize.python_path;

    for site_packages in find_site_packages()? {
        python_path.push(
            site_packages
                .to_str()
                .context("non-UTF-8 site-packages name")?
                .to_owned(),
        );
    }

    Runtime::new()?.block_on(
        ComponentGenerator {
            wit_paths: &common
                .wit_path
                .iter()
                .map(|v| v.as_path())
                .collect::<Vec<_>>(),
            worlds: &common.world.iter().map(|v| v.as_str()).collect::<Vec<_>>(),
            features: &common
                .features
                .iter()
                .map(|v| v.as_str())
                .collect::<Vec<_>>(),
            all_features: common.all_features,
            bindings_module: common.bindings_module.as_deref(),
            python_path: &python_path.iter().map(|s| s.as_str()).collect::<Vec<_>>(),
            module_worlds: &componentize
                .module_worlds
                .iter()
                .map(|(k, v)| (k.as_str(), [v.as_str()]))
                .collect::<Vec<_>>()
                .iter()
                .map(|(k, v)| (*k, v as &[_]))
                .collect::<Vec<_>>(),
            app_name: &componentize.app_name,
            output_path: &componentize.output,
            add_to_linker: None,
            stub_wasi: componentize.stub_wasi,
            import_interface_names: &common
                .import_interface_name
                .iter()
                .map(|(a, b)| (a.as_str(), b.as_str()))
                .collect(),
            export_interface_names: &common
                .export_interface_name
                .iter()
                .map(|(a, b)| (a.as_str(), b.as_str()))
                .collect(),
            intersect_world: componentize.intersect_world.as_deref(),
        }
        .generate(),
    )?;

    if !common.quiet {
        println!("Component built successfully");
    }

    Ok(())
}

fn find_site_packages() -> Result<Vec<PathBuf>> {
    Ok(if let Ok(env) = env::var("VIRTUAL_ENV") {
        let dir = Path::new(&env).join("lib");

        if let Some(site_packages) = find_dir("site-packages", &dir)? {
            vec![site_packages]
        } else {
            eprintln!(
                "warning: site-packages directory not found under {}",
                dir.display()
            );
            Vec::new()
        }
    } else {
        let pipenv_packages = match process::Command::new("pipenv").arg("--venv").output() {
            Ok(output) => {
                if output.status.success() {
                    let dir = Path::new(str::from_utf8(&output.stdout)?.trim()).join("lib");

                    if let Some(site_packages) = find_dir("site-packages", &dir)? {
                        vec![site_packages]
                    } else {
                        eprintln!(
                            "warning: site-packages directory not found under {}",
                            dir.display()
                        );
                        Vec::new()
                    }
                } else {
                    // `pipenv` is in `$PATH`, but this app does not appear to be using it
                    Vec::new()
                }
            }
            Err(_) => {
                // `pipenv` is not in `$PATH -- assume this app isn't using it
                Vec::new()
            }
        };

        if !pipenv_packages.is_empty() {
            pipenv_packages
        } else {
            // Get site packages location using the `site` module in python
            match process::Command::new("python3")
                .args([
                    "-c",
                    "import site; \
                     list = site.getsitepackages(); \
                     list.insert(0, site.getusersitepackages()); \
                     print(';'.join(list))",
                ])
                .output()
            {
                Ok(output) => str::from_utf8(&output.stdout)?
                    .trim()
                    .split(';')
                    .map(|p| Path::new(p).to_path_buf())
                    .collect(),
                Err(_) => Vec::new(),
            }
        }
    })
}

fn find_dir(name: &str, path: &Path) -> Result<Option<PathBuf>> {
    if path.is_dir() {
        match path.file_name().and_then(|name| name.to_str()) {
            Some(this_name) if this_name == name => {
                return Ok(Some(path.canonicalize()?));
            }
            _ => {
                for entry in fs::read_dir(path)? {
                    if let Some(path) = find_dir(name, &entry?.path())? {
                        return Ok(Some(path));
                    }
                }
            }
        }
    }

    Ok(None)
}

#[cfg(test)]
mod tests {
    use std::io::Write;

    use super::*;

    /// Generates a WIT file which has unstable feature "x"
    fn gated_x_wit_file() -> Result<tempfile::NamedTempFile, anyhow::Error> {
        let mut wit = tempfile::Builder::new()
            .prefix("gated")
            .suffix(".wit")
            .tempfile()?;
        write!(
            wit,
            r#"
            package foo:bar@1.2.3;

            world bindings {{
                @unstable(feature = x)
                import x: func();
                @since(version = 1.2.3)
                export y: func();
            }}
        "#,
        )?;
        Ok(wit)
    }

    #[test]
    fn unstable_bindings_not_generated() -> Result<()> {
        // Given a WIT file with gated features
        let wit = gated_x_wit_file()?;
        let out_dir = tempfile::tempdir()?;

        // When generating the bindings for this WIT world
        let common = Common {
            wit_path: vec![wit.path().into()],
            world: Vec::new(),
            bindings_module: Some("bindings".into()),
            quiet: false,
            features: vec![],
            all_features: false,
            import_interface_name: Vec::new(),
            export_interface_name: Vec::new(),
        };
        let bindings = Bindings {
            output_dir: out_dir.path().into(),
        };
        generate_bindings(common, bindings)?;

        // Then the gated feature doesn't appear
        let generated = fs::read_to_string(out_dir.path().join("bindings/__init__.py"))?;

        assert!(!generated.contains("def x() -> None:"));

        Ok(())
    }

    #[test]
    fn unstable_bindings_generated_with_feature_flag() -> Result<()> {
        // Given a WIT file with gated features
        let wit = gated_x_wit_file()?;
        let out_dir = tempfile::tempdir()?;

        // When generating the bindings for this WIT world
        let common = Common {
            wit_path: vec![wit.path().into()],
            world: Vec::new(),
            bindings_module: Some("bindings".into()),
            quiet: false,
            features: vec!["x".to_owned()],
            all_features: false,
            import_interface_name: Vec::new(),
            export_interface_name: Vec::new(),
        };
        let bindings = Bindings {
            output_dir: out_dir.path().into(),
        };
        generate_bindings(common, bindings)?;

        // Then the gated feature doesn't appear
        let generated = fs::read_to_string(out_dir.path().join("bindings/__init__.py"))?;

        assert!(generated.contains("def x() -> None:"));

        Ok(())
    }

    #[test]
    fn unstable_bindings_generated_for_all_features() -> Result<()> {
        // Given a WIT file with gated features
        let wit = gated_x_wit_file()?;
        let out_dir = tempfile::tempdir()?;

        // When generating the bindings for this WIT world
        let common = Common {
            wit_path: vec![wit.path().into()],
            world: Vec::new(),
            bindings_module: Some("bindings".into()),
            quiet: false,
            features: vec![],
            all_features: true,
            import_interface_name: Vec::new(),
            export_interface_name: Vec::new(),
        };
        let bindings = Bindings {
            output_dir: out_dir.path().into(),
        };
        generate_bindings(common, bindings)?;

        // Then the gated feature doesn't appear
        let generated = fs::read_to_string(out_dir.path().join("bindings/__init__.py"))?;

        assert!(generated.contains("def x() -> None:"));

        Ok(())
    }

    #[test]
    fn unstable_features_used_in_componentize() -> Result<()> {
        // Given bindings to a WIT file with gated features and a Python file
        // that uses them
        let wit = gated_x_wit_file()?;
        let out_dir = tempfile::tempdir()?;
        let common = Common {
            wit_path: vec![wit.path().into()],
            world: Vec::new(),
            bindings_module: Some("bindings".into()),
            quiet: false,
            features: vec!["x".to_owned()],
            all_features: false,
            import_interface_name: Vec::new(),
            export_interface_name: Vec::new(),
        };
        let bindings = Bindings {
            output_dir: out_dir.path().into(),
        };
        generate_bindings(common.clone(), bindings)?;
        fs::write(
            out_dir.path().join("app.py"),
            r#"
import bindings
from bindings import x

@bindings.guest
class Bindings(bindings.WorldExports):
    def y(self) -> None:
        x()
"#,
        )?;

        // Building the component succeeds
        let componentize_opts = Componentize {
            app_name: "app".to_owned(),
            python_path: vec![out_dir.path().to_string_lossy().into()],
            module_worlds: vec![],
            output: out_dir.path().join("app.wasm"),
            stub_wasi: false,
            intersect_world: None,
        };
        componentize(common, componentize_opts)
    }

    #[test]
    fn mix_of_cli_and_dependency_wits_and_worlds() -> Result<()> {
        let dir = tempfile::tempdir()?;

        let cli_wit_file = dir.path().join("cli.wit");
        fs::write(
            &cli_wit_file,
            br#"
package test:cli;

interface cli-interface {
  foo: func();
}

world cli-world {
  import cli-interface;
  export cli-interface;
  export foo: func();
}
"#,
        )?;

        let app_file = dir.path().join("app.py");
        fs::write(
            &app_file,
            br#"
import cli_world
from cli_world.exports.test import cli as exports
from cli_world.exports.test.cli import cli_interface as cli_iface
from cli_world.imports.test.cli import cli_interface
from lib.wit.imports.test.lib import lib_interface

@cli_world.guest
class CliWorld(cli_world.WorldExports):
    def foo(self) -> None:
        pass

@cli_iface.guest
class CliInterface(exports.CliInterface):
    def foo(self) -> None:
        lib_interface.foo()
        cli_interface.foo()
"#,
        )?;

        let lib_dir = dir.path().join("lib");
        let lib_wit_dir = lib_dir.join("wit");
        fs::create_dir_all(&lib_wit_dir)?;

        fs::write(
            lib_dir.join("componentize-py.toml"),
            br#"
wit_directory = "wit"
bindings = "wit"
"#,
        )?;

        fs::write(
            lib_wit_dir.join("lib.wit"),
            br#"
package test:lib;

interface lib-interface {
  foo: func();
}

world lib-world {
  import lib-interface;
}
"#,
        )?;

        generate_bindings(
            Common {
                wit_path: vec![lib_wit_dir.clone()],
                world: vec!["test:lib/lib-world".into()],
                bindings_module: Some("lib.wit".into()),
                quiet: false,
                features: Vec::new(),
                all_features: false,
                import_interface_name: Vec::new(),
                export_interface_name: Vec::new(),
            },
            Bindings {
                output_dir: lib_wit_dir,
            },
        )?;

        componentize(
            Common {
                wit_path: vec![cli_wit_file],
                world: vec!["test:cli/cli-world".into(), "test:lib/lib-world".into()],
                bindings_module: Some("cli_world".into()),
                quiet: false,
                features: Vec::new(),
                all_features: false,
                import_interface_name: Vec::new(),
                export_interface_name: Vec::new(),
            },
            Componentize {
                app_name: "app".into(),
                python_path: vec![
                    dir.path()
                        .to_str()
                        .ok_or_else(|| anyhow::anyhow!("non-UTF8 path"))?
                        .into(),
                ],
                module_worlds: vec![],
                output: dir.path().join("app.wasm"),
                stub_wasi: false,
                intersect_world: None,
            },
        )
    }

    fn common(wit_path: PathBuf, world: &str) -> Common {
        Common {
            wit_path: vec![wit_path],
            world: vec![world.to_owned()],
            bindings_module: None,
            quiet: false,
            features: vec![],
            all_features: false,
            import_interface_name: Vec::new(),
            export_interface_name: Vec::new(),
        }
    }

    fn bindings_error(dir: &tempfile::TempDir, wit: &str, world: &str) -> String {
        let wit_file = dir.path().join("test.wit");
        fs::write(&wit_file, wit).unwrap();
        let out_dir = dir.path().join("out");
        fs::create_dir(&out_dir).unwrap();

        format!(
            "{:?}",
            generate_bindings(
                common(wit_file, world),
                Bindings {
                    output_dir: out_dir,
                },
            )
            .expect_err("bindings generation should fail")
        )
    }

    #[test]
    fn function_named_guest_in_exported_interface_is_allowed() -> Result<()> {
        // Exported functions become ABC methods and cannot clash with `guest`.
        let dir = tempfile::tempdir()?;
        let wit_file = dir.path().join("test.wit");
        fs::write(
            &wit_file,
            r#"
package my:root;
world w {
    export bad: interface {
        guest: func();
    }
}
"#,
        )?;
        let out_dir = dir.path().join("out");
        fs::create_dir(&out_dir)?;

        generate_bindings(
            common(wit_file, "w"),
            Bindings {
                output_dir: out_dir,
            },
        )
    }

    #[test]
    fn reserved_guest_name_as_world_import() -> Result<()> {
        let dir = tempfile::tempdir()?;
        let error = bindings_error(
            &dir,
            r#"
package my:root;
world w {
    import guest: func();
    export f: func();
}
"#,
            "w",
        );

        assert!(error.contains("reserved `guest` decorator"), "{error}");

        Ok(())
    }

    #[test]
    fn conflicting_interface_name_overrides() -> Result<()> {
        let dir = tempfile::tempdir()?;
        let wit_file = dir.path().join("test.wit");
        fs::write(
            &wit_file,
            r#"
package my:root;
interface a { f: func(); }
interface b { g: func(); }
world w {
    import a;
    import b;
}
"#,
        )?;
        let out_dir = dir.path().join("out");
        fs::create_dir(&out_dir)?;

        let mut common = common(wit_file, "w");
        common.import_interface_name = vec![
            ("my:root/a".to_owned(), "dup".to_owned()),
            ("my:root/b".to_owned(), "dup".to_owned()),
        ];

        let error = format!(
            "{:?}",
            generate_bindings(
                common,
                Bindings {
                    output_dir: out_dir,
                },
            )
            .expect_err("bindings generation should fail")
        );

        assert!(error.contains("map to the module alias `dup`"), "{error}");

        Ok(())
    }

    #[test]
    fn interface_module_shadowed_by_package() -> Result<()> {
        // `foo` would be both `imports/foo.py` and package `imports/foo/`.
        let dir = tempfile::tempdir()?;
        fs::create_dir_all(dir.path().join("wit/deps/dep"))?;
        fs::write(
            dir.path().join("wit/root.wit"),
            r#"
package my:root;
world w {
    import foo: interface { f: func(); }
    import foo:bar/baz;
}
"#,
        )?;
        fs::write(
            dir.path().join("wit/deps/dep/dep.wit"),
            r#"
package foo:bar;
interface baz { g: func(); }
"#,
        )?;
        let out_dir = dir.path().join("out");
        fs::create_dir(&out_dir)?;

        let error = format!(
            "{:?}",
            generate_bindings(
                common(dir.path().join("wit"), "w"),
                Bindings {
                    output_dir: out_dir,
                },
            )
            .expect_err("bindings generation should fail")
        );

        assert!(
            error.contains("would be shadowed by the package"),
            "{error}"
        );

        Ok(())
    }

    #[test]
    fn canonical_version_collision_fallback() -> Result<()> {
        // Same canonical version (`v0-1`) twice: fall back to full versions.
        let dir = tempfile::tempdir()?;
        fs::create_dir_all(dir.path().join("wit/deps/a"))?;
        fs::create_dir_all(dir.path().join("wit/deps/b"))?;
        fs::write(
            dir.path().join("wit/root.wit"),
            r#"
package my:root;
world w {
    import foo:bar/baz@0.1.1;
    import foo:bar/baz@0.1.2;
}
"#,
        )?;
        fs::write(
            dir.path().join("wit/deps/a/a.wit"),
            "package foo:bar@0.1.1;\ninterface baz { f: func(); }",
        )?;
        fs::write(
            dir.path().join("wit/deps/b/b.wit"),
            "package foo:bar@0.1.2;\ninterface baz { g: func(); }",
        )?;
        let out_dir = dir.path().join("out");
        fs::create_dir(&out_dir)?;

        generate_bindings(
            common(dir.path().join("wit"), "w"),
            Bindings {
                output_dir: out_dir.clone(),
            },
        )?;

        assert!(out_dir.join("wit/imports/foo/bar_v0_1_1/baz.py").is_file());
        assert!(out_dir.join("wit/imports/foo/bar_v0_1_2/baz.py").is_file());

        Ok(())
    }

    #[test]
    fn dotted_interface_name_override() -> Result<()> {
        let dir = tempfile::tempdir()?;
        let wit_file = dir.path().join("test.wit");
        fs::write(
            &wit_file,
            r#"
package my:root;
interface a { f: func(); }
world w {
    import a;
}
"#,
        )?;
        let out_dir = dir.path().join("out");
        fs::create_dir(&out_dir)?;

        let mut common = common(wit_file, "w");
        common.import_interface_name =
            vec![("my:root/a".to_owned(), "my_pkg.my_module".to_owned())];

        generate_bindings(
            common,
            Bindings {
                output_dir: out_dir.clone(),
            },
        )?;

        assert!(out_dir.join("wit/imports/my_pkg/my_module.py").is_file());

        Ok(())
    }

    #[test]
    fn dotted_bindings_module() -> Result<()> {
        let dir = tempfile::tempdir()?;
        let wit_file = dir.path().join("test.wit");
        fs::write(
            &wit_file,
            r#"
package my:root;
world w {
    export f: func();
}
"#,
        )?;
        let out_dir = dir.path().join("out");
        fs::create_dir(&out_dir)?;

        let mut common = common(wit_file, "w");
        common.bindings_module = Some("my.pkg".into());

        generate_bindings(
            common,
            Bindings {
                output_dir: out_dir.clone(),
            },
        )?;

        assert!(out_dir.join("my/__init__.py").is_file());
        assert!(out_dir.join("my/pkg/__init__.py").is_file());
        let generated = fs::read_to_string(out_dir.join("my/pkg/__init__.py"))?;
        assert!(generated.contains("guest ="), "{generated}");

        Ok(())
    }

    #[test]
    fn helper_placeholders_follow_the_generated_paths() -> Result<()> {
        // Both the module and the interface paths come from what was generated.
        let dir = tempfile::tempdir()?;
        let out_dir = dir.path().join("out");
        fs::create_dir(&out_dir)?;

        let mut common = common("wit".into(), "wasi:http/proxy@0.2.0");
        common.bindings_module = Some("my.pkg".into());

        generate_bindings(
            common,
            Bindings {
                output_dir: out_dir.clone(),
            },
        )?;

        let generated = fs::read_to_string(out_dir.join("poll_loop.py"))?;
        for expected in [
            "import my.pkg.imports.wasi.http_v0_2.types as types",
            "import my.pkg.imports.wasi.io_v0_2.poll as poll",
            "from my.pkg.imports.wasi.io_v0_2.streams import StreamError_Closed, InputStream",
        ] {
            assert!(generated.contains(expected), "{generated}");
        }
        assert!(!generated.contains("WASI_HTTP_TYPES_MODULE"), "{generated}");

        Ok(())
    }

    #[test]
    fn helper_placeholders_kept_when_interfaces_are_absent() -> Result<()> {
        // Nothing to point the helpers at, so leave the names greppable.
        let dir = tempfile::tempdir()?;
        let wit_file = dir.path().join("test.wit");
        fs::write(
            &wit_file,
            r#"
package my:root;
world w {
    export f: func();
}
"#,
        )?;
        let out_dir = dir.path().join("out");
        fs::create_dir(&out_dir)?;

        generate_bindings(
            common(wit_file, "w"),
            Bindings {
                output_dir: out_dir.clone(),
            },
        )?;

        let generated = fs::read_to_string(out_dir.join("poll_loop.py"))?;
        assert!(
            generated.contains("import WASI_HTTP_TYPES_MODULE as types"),
            "{generated}"
        );

        Ok(())
    }

    #[test]
    fn export_resource_classvar_uses_export_side() -> Result<()> {
        // The resource `ClassVar` must reference the export-side class.
        let dir = tempfile::tempdir()?;
        let wit_file = dir.path().join("test.wit");
        fs::write(
            &wit_file,
            r#"
package my:root;
interface i {
    resource r {
        constructor();
    }
    f: func(v: r);
}
world w {
    import i;
    export i;
}
"#,
        )?;
        let out_dir = dir.path().join("out");
        fs::create_dir(&out_dir)?;

        generate_bindings(
            common(wit_file, "w"),
            Bindings {
                output_dir: out_dir.clone(),
            },
        )?;

        let generated = fs::read_to_string(out_dir.join("wit/exports/my/root/__init__.py"))?;
        assert!(
            generated.contains("from .i import R as _my_root_i_r"),
            "{generated}"
        );
        assert!(
            generated.contains("r: ClassVar[type[_my_root_i_r]]"),
            "{generated}"
        );
        // Packages expose their own submodules.
        assert!(generated.contains("from . import i"), "{generated}");

        Ok(())
    }

    #[test]
    fn cross_direction_alias_collision() -> Result<()> {
        // Flat aliases share one namespace across directions.
        let dir = tempfile::tempdir()?;
        let error = bindings_error(
            &dir,
            r#"
package my:root;
interface b { g: func(); }
world w {
    import b;
    export my-root-b: interface {
        f: func();
    }
}
"#,
            "w",
        );

        assert!(error.contains("module alias `my_root_b`"), "{error}");

        Ok(())
    }

    #[test]
    fn reserved_world_exports_name() -> Result<()> {
        let dir = tempfile::tempdir()?;
        let error = bindings_error(
            &dir,
            r#"
package my:root;
interface x {
    record world-exports { x: u32 }
}
world w {
    use x.{world-exports};
    export f: func(v: world-exports);
}
"#,
            "w",
        );

        assert!(error.contains("reserved `WorldExports` class"), "{error}");

        Ok(())
    }

    #[test]
    fn cross_direction_version_fallback() -> Result<()> {
        // Cross-direction canonical ties fall back instead of erroring.
        let dir = tempfile::tempdir()?;
        fs::create_dir_all(dir.path().join("wit/deps/a"))?;
        fs::create_dir_all(dir.path().join("wit/deps/b"))?;
        fs::write(
            dir.path().join("wit/root.wit"),
            r#"
package my:root;
world w {
    import foo:bar/baz@0.1.1;
    export foo:bar/baz@0.1.2;
}
"#,
        )?;
        fs::write(
            dir.path().join("wit/deps/a/a.wit"),
            "package foo:bar@0.1.1;\ninterface baz { f: func(); }",
        )?;
        fs::write(
            dir.path().join("wit/deps/b/b.wit"),
            "package foo:bar@0.1.2;\ninterface baz { g: func(); }",
        )?;
        let out_dir = dir.path().join("out");
        fs::create_dir(&out_dir)?;

        generate_bindings(
            common(dir.path().join("wit"), "w"),
            Bindings {
                output_dir: out_dir.clone(),
            },
        )?;

        assert!(out_dir.join("wit/imports/foo/bar_v0_1_1/baz.py").is_file());
        assert!(out_dir.join("wit/exports/foo/bar_v0_1_2/baz.py").is_file());

        Ok(())
    }

    #[test]
    fn reserved_guest_name_as_interface_alias() -> Result<()> {
        let dir = tempfile::tempdir()?;
        let error = bindings_error(
            &dir,
            r#"
package my:root;
world w {
    import guest: interface {
        f: func();
    }
}
"#,
            "w",
        );

        assert!(error.contains("reserved `guest` decorator"), "{error}");

        Ok(())
    }

    #[test]
    fn invalid_interface_name_override() -> Result<()> {
        let dir = tempfile::tempdir()?;
        let wit_file = dir.path().join("test.wit");
        fs::write(
            &wit_file,
            r#"
package my:root;
interface a { f: func(); }
world w {
    import a;
}
"#,
        )?;
        let out_dir = dir.path().join("out");
        fs::create_dir(&out_dir)?;

        let mut common = common(wit_file, "w");
        common.import_interface_name = vec![("my:root/a".to_owned(), "1foo".to_owned())];

        let error = format!(
            "{:?}",
            generate_bindings(
                common,
                Bindings {
                    output_dir: out_dir,
                },
            )
            .expect_err("bindings generation should fail")
        );

        assert!(error.contains("not a valid Python identifier"), "{error}");

        Ok(())
    }

    #[test]
    fn invalid_bindings_module() -> Result<()> {
        let dir = tempfile::tempdir()?;
        let wit_file = dir.path().join("test.wit");
        fs::write(
            &wit_file,
            r#"
package my:root;
world w {
    export f: func();
}
"#,
        )?;
        let out_dir = dir.path().join("out");
        fs::create_dir(&out_dir)?;

        let mut common = common(wit_file, "w");
        common.bindings_module = Some("my-module".into());

        let error = format!(
            "{:?}",
            generate_bindings(
                common,
                Bindings {
                    output_dir: out_dir,
                },
            )
            .expect_err("bindings generation should fail")
        );

        assert!(error.contains("not a valid Python module path"), "{error}");

        Ok(())
    }

    #[test]
    fn exported_interface_named_after_bindings_module() -> Result<()> {
        let dir = tempfile::tempdir()?;
        let error = bindings_error(
            &dir,
            r#"
package my:root;
world w {
    export wit: interface {
        f: func();
    }
}
"#,
            "w",
        );

        assert!(
            error.contains("collides with the bindings module name"),
            "{error}"
        );

        Ok(())
    }

    #[test]
    fn world_level_export_named_guest_is_allowed() -> Result<()> {
        // Only world-level *imports* clash with the root `guest` decorator.
        let dir = tempfile::tempdir()?;
        let wit_file = dir.path().join("test.wit");
        fs::write(
            &wit_file,
            r#"
package my:root;
world w {
    export guest: func();
}
"#,
        )?;
        let out_dir = dir.path().join("out");
        fs::create_dir(&out_dir)?;

        generate_bindings(
            common(wit_file, "w"),
            Bindings {
                output_dir: out_dir,
            },
        )
    }

    #[test]
    fn keyword_bindings_module() -> Result<()> {
        let dir = tempfile::tempdir()?;
        let wit_file = dir.path().join("test.wit");
        fs::write(&wit_file, "package my:root;\nworld w { export f: func(); }")?;
        let out_dir = dir.path().join("out");
        fs::create_dir(&out_dir)?;

        let mut common = common(wit_file, "w");
        common.bindings_module = Some("class".into());

        let error = format!(
            "{:?}",
            generate_bindings(
                common,
                Bindings {
                    output_dir: out_dir,
                },
            )
            .expect_err("bindings generation should fail")
        );

        assert!(error.contains("not a valid Python module path"), "{error}");

        Ok(())
    }

    #[test]
    fn refuses_to_overwrite_wit_sources() -> Result<()> {
        // The default module (`wit`) must not clobber a `wit/` source dir.
        let dir = tempfile::tempdir()?;
        fs::create_dir(dir.path().join("wit"))?;
        fs::write(
            dir.path().join("wit/app.wit"),
            "package my:root;\nworld w { export f: func(); }",
        )?;

        let error = format!(
            "{:?}",
            generate_bindings(
                common(dir.path().join("wit"), "w"),
                Bindings {
                    output_dir: dir.path().into(),
                },
            )
            .expect_err("bindings generation should fail")
        );

        assert!(error.contains("contains WIT source files"), "{error}");

        Ok(())
    }

    #[test]
    fn override_used_verbatim() -> Result<()> {
        let dir = tempfile::tempdir()?;
        let wit_file = dir.path().join("test.wit");
        fs::write(
            &wit_file,
            "package my:root;\ninterface a { f: func(); }\nworld w { import a; }",
        )?;
        let out_dir = dir.path().join("out");
        fs::create_dir(&out_dir)?;

        let mut common = common(wit_file, "w");
        common.import_interface_name = vec![("my:root/a".to_owned(), "myPkg.myModule".to_owned())];

        generate_bindings(
            common,
            Bindings {
                output_dir: out_dir.clone(),
            },
        )?;

        assert!(out_dir.join("wit/imports/myPkg/myModule.py").is_file());

        Ok(())
    }

    #[test]
    fn rerun_into_same_directory() -> Result<()> {
        let dir = tempfile::tempdir()?;
        let wit_file = dir.path().join("test.wit");
        fs::write(
            &wit_file,
            "package my:root;\ninterface a { f: func(); }\nworld w { import a; export a; }",
        )?;
        let out_dir = dir.path().join("out");
        fs::create_dir(&out_dir)?;

        generate_bindings(
            common(wit_file.clone(), "w"),
            Bindings {
                output_dir: out_dir.clone(),
            },
        )?;

        // Rename the interface and regenerate into the same directory.
        fs::write(
            &wit_file,
            "package my:root;\ninterface b { f: func(); }\nworld w { import b; export b; }",
        )?;
        generate_bindings(
            common(wit_file, "w"),
            Bindings {
                output_dir: out_dir.clone(),
            },
        )?;

        // No duplicate submodule imports, and no stale modules.
        let generated = fs::read_to_string(out_dir.join("wit/imports/my/__init__.py"))?;
        assert_eq!(
            1,
            generated.matches("from . import root").count(),
            "{generated}"
        );
        assert!(!out_dir.join("wit/imports/my/root/a.py").exists());
        assert!(out_dir.join("wit/imports/my/root/b.py").is_file());

        Ok(())
    }

    #[test]
    fn refuses_to_overwrite_nested_wit_sources() -> Result<()> {
        // WIT sources under `wit/deps/...` must be detected too.
        let dir = tempfile::tempdir()?;
        let wit_file = dir.path().join("test.wit");
        fs::write(&wit_file, "package my:root;\nworld w { export f: func(); }")?;
        let out_dir = dir.path().join("out");
        fs::create_dir_all(out_dir.join("wit/deps/dep"))?;
        fs::write(
            out_dir.join("wit/deps/dep/dep.wit"),
            "package other:dep;\ninterface x { f: func(); }",
        )?;

        let error = format!(
            "{:?}",
            generate_bindings(
                common(wit_file, "w"),
                Bindings {
                    output_dir: out_dir,
                },
            )
            .expect_err("bindings generation should fail")
        );

        assert!(error.contains("contains WIT source files"), "{error}");

        Ok(())
    }

    #[test]
    fn world_import_named_exports_is_usable() -> Result<()> {
        // The import shadows the subpackage attribute, not vice versa.
        let dir = tempfile::tempdir()?;
        let wit_file = dir.path().join("test.wit");
        fs::write(
            &wit_file,
            "package my:root;\ninterface i { g: func(); }\nworld w { import exports: func(); import i; export i; }",
        )?;
        let out_dir = dir.path().join("out");
        fs::create_dir(&out_dir)?;

        generate_bindings(
            common(wit_file, "w"),
            Bindings {
                output_dir: out_dir.clone(),
            },
        )?;

        let generated = fs::read_to_string(out_dir.join("wit/__init__.py"))?;
        let bind = generated.find("from . import exports").unwrap();
        let def = generated.find("def exports").unwrap();
        assert!(bind < def, "{generated}");

        Ok(())
    }

    #[test]
    fn camel_case_export_override_rejected() -> Result<()> {
        let dir = tempfile::tempdir()?;
        let wit_file = dir.path().join("test.wit");
        fs::write(
            &wit_file,
            "package my:root;\ninterface a { f: func(); }\nworld w { export a; }",
        )?;
        let out_dir = dir.path().join("out");
        fs::create_dir(&out_dir)?;

        let mut common = common(wit_file, "w");
        common.export_interface_name = vec![("my:root/a".to_owned(), "Foo".to_owned())];

        let error = format!(
            "{:?}",
            generate_bindings(
                common,
                Bindings {
                    output_dir: out_dir,
                },
            )
            .expect_err("bindings generation should fail")
        );

        assert!(error.contains("abstract base class"), "{error}");

        Ok(())
    }
}
