name: Test
on:
  pull_request:
    branches: [main]
    paths-ignore:
      - "examples/**/README.md"
      - "README.md"
      - "CONTRIBUTING.md"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Test
    strategy:
      fail-fast: false
      matrix:
        config:
          - { os: "ubuntu-latest", wasiSDK: "x86_64-linux" }
          - { os: "macos-latest", wasiSDK: "arm64-macos" }
          - { os: "windows-latest", wasiSDK: "x86_64-windows" }
    runs-on: ${{ matrix.config.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: "recursive"

      - name: Install latest Rust toolchain
        # todo: switch back to stable once 1.100 is released:
        uses: dtolnay/rust-toolchain@nightly
        with:
          targets: wasm32-wasip2 wasm32-wasip3
          components: clippy, rustfmt

      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: "rust-cache-${{ hashFiles('./Cargo.lock') }}"
          cache-on-failure: false

      - name: Lint
        shell: bash
        run: bash .github/workflows/lint.sh

      - uses: taiki-e/install-action@v2
        with:
          tool: wasmtime-cli@48.0.2

      - uses: actions/setup-python@v5
        with:
          python-version: "3.14.0"

      - name: Test
        shell: bash
        run: COMPONENTIZE_PY_TEST_COUNT=20 PROPTEST_MAX_SHRINK_ITERS=0 cargo test --release
